version: "3.9"

services:
  mini-broker:
    build: ./mini-broker
    command: [ node, ./dist/server.js ]
    working_dir: /app
    restart: always
    ports:
      - "8883:${PORT:-8883}"
      - "8080:${WS_PORT:-8080}"
    env_file:
      - mini-broker/production.env
    networks:
      - laboratory

  device-passive-a:
    build: ./device
    command: [ node, ./dist/client.js ]
    working_dir: /app
    depends_on:
      - mini-broker
    restart: always
    env_file:
      - device/production.env
    environment:
      - DEVICE_NAME=device-passive-A
      - IS_PASSIVE=true
      - HOST=laboratory
    networks:
      - laboratory

  device-passive-b:
    build: ./device
    command: [ node, ./dist/client.js ]
    working_dir: /app
    depends_on:
      - mini-broker
    restart: always
    env_file:
      - device/production.env
    environment:
      - DEVICE_NAME=device-passive-B
      - IS_PASSIVE=true
      - HOST=laboratory
    networks:
      - laboratory

  device-active-a:
    build: ./device
    command: [ node, ./dist/client.js ]
    working_dir: /app
    depends_on:
      - mini-broker
    restart: always
    env_file:
      - device/production.env
    environment:
      - DEVICE_NAME=device-active-A
      - IS_PASSIVE=false
      - HOST=laboratory
    networks:
      - laboratory

  device-active-b:
    build: ./device
    command: [ node, ./dist/client.js ]
    working_dir: /app
    depends_on:
      - mini-broker
    restart: always
    env_file:
      - device/production.env
    environment:
      - DEVICE_NAME=device-active-B
      - IS_PASSIVE=false
      - HOST=laboratory
    networks:
      - laboratory

networks:
  laboratory:
